name: Rollback

on:
  workflow_dispatch:
#    inputs:
#      rollback_sha:
#        description: "Docker image SHA to rollback to"
#        required: true
#        type: string

permissions:
  actions: read
jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:

      - name: Find latest successful CI run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=$(gh run list \
            --workflow="Spring Boot CI" \
            --status=success \
            --limit=1 \
            --json databaseId \
            --jq '.[0].databaseId')
            
          echo "Latest successful run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Rollback on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd:${{ github.event.inputs.rollback_sha }}

            docker stop ci-cd || true
            docker rm ci-cd || true

            docker run -d \
              --name ci-cd \
              -p 8080:8080 \
              ${{ secrets.DOCKER_USERNAME }}/ci-cd:${{ github.event.inputs.rollback_sha }}